export const FETCHING_EMPLOYEES = 'FETCHING_EMPLOYEES';
export const FETCHING_EMPLOYEES_SUCCESS = 'FETCHING_EMPLOYEES_SUCCESS';
export const FETCHING_EMPLOYEES_FAILURE = 'FETCHING_EMPLOYEES_FAILURE';
export const CLEAR_LIST = 'CLEAR_LIST';